package autodev

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"time"

	"github.com/ymhhh/vibecoding/internal/gitx"
	"github.com/ymhhh/vibecoding/internal/model"
)

func (r *Runner) prDescription(issue model.Issue) string {
	if !issue.HasSubRequirements() {
		return "Auto-dev changes generated by Vibecoding (local branch review)."
	}
	var b strings.Builder
	b.WriteString("Sequential Auto-dev by Vibecoding.\n\nSub-requirements:\n")
	for _, sub := range issue.SubRequirements {
		sha := sub.CommitSHA
		if sha == "" {
			sha = string(sub.Status)
		}
		b.WriteString(fmt.Sprintf("- [%d] %s (%s)\n", sub.Order, sub.Title, sha))
	}
	return b.String()
}

func (r *Runner) collectDiffStats(repos []model.GitRepo) model.DiffStats {
	var stats model.DiffStats
	for _, repo := range repos {
		st, _ := gitx.DiffStats(repo.Path, repo.DefaultBranch)
		stats.Additions += st.Additions
		stats.Deletions += st.Deletions
		stats.FilesChanged += st.FilesChanged
	}
	return stats
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}

// runTests returns output, how (configured / auto-detected label), skipped, err.
func runTests(repo model.GitRepo) (output, how string, skipped bool, err error) {
	if cmdline := strings.TrimSpace(repo.TestCommand); cmdline != "" {
		out, err := runShellCommand(repo.Path, cmdline)
		return out, "configured: " + cmdline, false, err
	}
	switch {
	case fileExists(filepath.Join(repo.Path, "go.mod")):
		out, skipped, err := runCmd(repo.Path, "go", "test", "./...")
		if skipped {
			return out, "", true, nil
		}
		if err != nil && strings.Contains(out, "no packages to test") {
			return out, "auto-detected: go test ./...", true, nil
		}
		return out, "auto-detected: go test ./...", false, err
	case fileExists(filepath.Join(repo.Path, "package.json")):
		if fileExists(filepath.Join(repo.Path, "pnpm-lock.yaml")) {
			out, skipped, err := runCmd(repo.Path, "pnpm", "test", "--if-present")
			return out, "auto-detected: pnpm test --if-present", skipped, err
		}
		out, skipped, err := runCmd(repo.Path, "npm", "test", "--if-present")
		return out, "auto-detected: npm test --if-present", skipped, err
	case fileExists(filepath.Join(repo.Path, "pyproject.toml")) || fileExists(filepath.Join(repo.Path, "pytest.ini")):
		out, skipped, err := runCmd(repo.Path, "pytest", "-q")
		return out, "auto-detected: pytest -q", skipped, err
	default:
		return "", "", true, nil
	}
}

func runLint(repo model.GitRepo) (output, how string, skipped bool, err error) {
	if cmdline := strings.TrimSpace(repo.LintCommand); cmdline != "" {
		out, err := runShellCommand(repo.Path, cmdline)
		return out, "configured: " + cmdline, false, err
	}
	if fileExists(filepath.Join(repo.Path, "go.mod")) {
		out, skipped, err := runCmd(repo.Path, "go", "vet", "./...")
		return out, "auto-detected: go vet ./...", skipped, err
	}
	if fileExists(filepath.Join(repo.Path, "tsconfig.json")) {
		out, skipped, err := runCmd(repo.Path, "npx", "--no-install", "tsc", "--noEmit")
		return out, "auto-detected: npx tsc --noEmit", skipped, err
	}
	return "", "", true, nil
}

func runShellCommand(dir, cmdline string) (string, error) {
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()
	var cmd *exec.Cmd
	if runtime.GOOS == "windows" {
		cmd = exec.CommandContext(ctx, "cmd", "/c", cmdline)
	} else {
		cmd = exec.CommandContext(ctx, "sh", "-c", cmdline)
	}
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	return string(out), err
}

func runCmd(dir, name string, args ...string) (string, bool, error) {
	if _, err := exec.LookPath(name); err != nil {
		return "", true, nil
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	return string(out), false, err
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n]
}
