package autodev

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/ymhhh/vibecoding/internal/gitx"
	"github.com/ymhhh/vibecoding/internal/model"
)

func (r *Runner) prDescription(issue model.Issue) string {
	if !issue.HasSubRequirements() {
		return "Auto-dev changes generated by Vibecoding (local branch review)."
	}
	var b strings.Builder
	b.WriteString("Sequential Auto-dev by Vibecoding.\n\nSub-requirements:\n")
	for _, sub := range issue.SubRequirements {
		sha := sub.CommitSHA
		if sha == "" {
			sha = string(sub.Status)
		}
		b.WriteString(fmt.Sprintf("- [%d] %s (%s)\n", sub.Order, sub.Title, sha))
	}
	return b.String()
}

func (r *Runner) collectDiffStats(repos []model.GitRepo) model.DiffStats {
	var stats model.DiffStats
	for _, repo := range repos {
		st, _ := gitx.DiffStats(repo.Path, repo.DefaultBranch)
		stats.Additions += st.Additions
		stats.Deletions += st.Deletions
		stats.FilesChanged += st.FilesChanged
	}
	return stats
}

func firstNonEmpty(vals ...string) string {
	for _, v := range vals {
		if strings.TrimSpace(v) != "" {
			return v
		}
	}
	return ""
}

func runTests(repo model.GitRepo) (output string, skipped bool, err error) {
	switch {
	case fileExists(filepath.Join(repo.Path, "go.mod")):
		out, skipped, err := runCmd(repo.Path, "go", "test", "./...")
		if skipped {
			return out, true, nil
		}
		// Empty modules (go.mod only) report "no packages to test" with exit 1.
		if err != nil && strings.Contains(out, "no packages to test") {
			return out, true, nil
		}
		return out, false, err
	case fileExists(filepath.Join(repo.Path, "package.json")):
		// prefer npm test if script exists — just try
		if fileExists(filepath.Join(repo.Path, "pnpm-lock.yaml")) {
			return runCmd(repo.Path, "pnpm", "test", "--if-present")
		}
		return runCmd(repo.Path, "npm", "test", "--if-present")
	case fileExists(filepath.Join(repo.Path, "pyproject.toml")) || fileExists(filepath.Join(repo.Path, "pytest.ini")):
		return runCmd(repo.Path, "pytest", "-q")
	default:
		return "", true, nil
	}
}

func runLint(repo model.GitRepo) (output string, skipped bool, err error) {
	if fileExists(filepath.Join(repo.Path, "go.mod")) {
		return runCmd(repo.Path, "go", "vet", "./...")
	}
	if fileExists(filepath.Join(repo.Path, "tsconfig.json")) {
		return runCmd(repo.Path, "npx", "--no-install", "tsc", "--noEmit")
	}
	return "", true, nil
}

func runCmd(dir, name string, args ...string) (string, bool, error) {
	if _, err := exec.LookPath(name); err != nil {
		return "", true, nil
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Minute)
	defer cancel()
	cmd := exec.CommandContext(ctx, name, args...)
	cmd.Dir = dir
	out, err := cmd.CombinedOutput()
	return string(out), false, err
}

func fileExists(p string) bool {
	_, err := os.Stat(p)
	return err == nil
}

func truncate(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n]
}
